name: webhook testing announcements



on: 
    repository_dispatch:
        types: [announcement_launched]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Check AppsAway version
          run: if [ "${{ github.event.client_payload.type }}" == "announcement_launched" ]; then echo '${{ github.event.client_payload.description }}'; fi

        - run: |
                if [ "${{ github.event.client_payload.type }}" == "announcement_launched" ]
                then
                  echo '${{ github.event.client_payload.description }}' > temp.md  # create two example files
                fi
        - uses: docker://pandoc/latex:2.9
          with:
            args: --output=result.html temp.md
        - name: populate the DB
          run: |
                if [ "${{ github.event.client_payload.type }}" == "announcement_launched" ]
                then
                  announce=$(cat result.html)
                  echo "$announce"
                  echo '{' >> test.json
                  echo '"id"            : "${{ github.event.client_payload.id }}",' >> test.json
                  echo '"title"         : "${{ github.event.client_payload.title }}",' >> test.json
                  echo '"date"          : "${{ github.event.client_payload.date }}",' >> test.json
                  echo '"summary"       : "${{ github.event.client_payload.summary }}",' >> test.json
                  echo "\"description\"   : \"$(cat result.html)\"," >> test.json
                  echo '"image"         : "${{ github.event.client_payload.image }}"' >> test.json
                  echo '}' >> test.json
                fi
        - name: commit the file
          run: |
                if [ "${{ github.event.client_payload.type }}" == "announcement_launched" ]
                then
                  git config --local user.email "actions@github.com"
                  git config --local user.name "GitHub Action"
                  git add result.html test.json
                  git commit -m "updated announcement file"
                fi


        - name: push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}






