name: webhook testing announcements



on: 
    repository_dispatch:
        types: [announcement_launched]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: populate the DB
          env:
            DESCRIPTION_CONTEXT: ${{ toJson(github.event.client_payload.description) }}
          run: |
                if [ "${{ github.event.client_payload.type }}" == "announcement_launched" ]
                then
                  echo $DESCRIPTION_CONTEXT > temp.txt
                  awk -v ORS='\\n' '1' temp.txt > temp1.txt
                  sed 's/\r//g' temp1.txt > temp2.txt
                  announce="$(cat temp2.txt)"
                  echo '{' >> test.json
                  echo '"id"            : "${{ github.event.client_payload.id }}",' >> test.json
                  echo '"title"         : "${{ github.event.client_payload.title }}",' >> test.json
                  echo '"date"          : "${{ github.event.client_payload.date }}",' >> test.json
                  echo '"summary"       : "${{ github.event.client_payload.summary }}",' >> test.json
                  echo "\"description\"   : \"$announce \"," >> test.json
                  if [[ "${{ github.event.client_payload.release }}" == "true" ]]
                  then
                    echo '"image"         : "default image for release"' >> test.json
                  else
                    echo '"image"         : "default image for announcement"' >> test.json
                  fi
                  echo '}' >> test.json
                fi
        - name: commit the file
          run: |
                if [ "${{ github.event.client_payload.type }}" == "announcement_launched" ]
                then
                  git config --local user.email "actions@github.com"
                  git config --local user.name "GitHub Action"
                  git add test.json
                  git commit -m "updated announcement file"
                fi


        - name: push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}






