name: load json file

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Define variables
              run: |
                  # Hard coded variable
                  echo "./SB_version.json" > VERSIONFILE_NAME
                  #
                  # Logically defined variable from the Dockerfile
                  cat $(cat VERSIONFILE_NAME) | grep -Pio 'v[1-9]{1,}\..{1,}(?=\"\})' > VERSION_TEST

            - run: echo "tag = $(cat VERSION_TEST)"
            - run: echo "$(date +'%d')"

