name: load json file

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo ${VERSION_TEST}
              env:
                  VERSION_TEST: $(cat ./SB_version.json | grep '"version" :'= | head -n 1 | grep -Pio 'v[1-9]{1,}\..{1,}(?=\"\})') #| sed 's/"//g')
                  #vari: eval $(grep -Pio 'v[1-9]{1,}\..{1,}(?=\"\})' ./SB_version.json)
            - run:  ${VERSION_TEST}
              env: 
                    VERSION_TEST: $(grep -Pio 'v[1-9]{1,}\..{1,}(?=\"\})' ./SB_version.json)
            - run: grep -Pio 'v[1-9]{1,}\..{1,}(?=\"\})' ./SB_version.json

