# this workflow will generate the containers on push. These containers are for test only, so ideally they should be uploaded to a private repo, not available to the public. tag=superbuild_devel (?)
# for the stable versions, use superbuild_builder_stable.yml, triggered on release

name: onCodeChanges

on: 
    push
    
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                apps: [superbuild, superbuild-icubhead]
                include:
                - version: master
                  tag: stable
                - version: master
                  tag: unstable
                - version: release
                  tag: ""

        steps:
            - uses: actions/checkout@v2

##################### Command to set the tag for the date argument ######################
            - name: set date argument for Docker build
              run: |
                echo "$(date +'%d/%m/%Y')" > DATE_
                echo "metadata=$(cat DATE_)" > DATE_TAG
                echo $(cat DATE_TAG)
#########################################################################################

            - name: Get last Superbuild version
              if: ${{ matrix.version }} == 'release' 
              id: get_version
              run: echo ::set-output name=VERSION::release=$( if [ ${{ matrix.version }} == 'release' ]; then echo "./SB_version.json" > VERSIONFILE_NAME && cat $(cat VERSIONFILE_NAME) | grep -Pio 'v[1-9]{1,}.{1,}(?=\"\})'; else echo "master-${{ matrix.tag }}"; fi)

            - name: Print result
              run: echo ${{ steps.get_version.outputs.VERSION }}
